# Site settings
title: Sam Wong
email: samw627@uw.edu
description: > # this means to ignore newlines until "baseurl:"
   HCI researcher at Social Futures Lab, Paul.G. Allen School of Computer Science & Engineering, University of Washington.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samw0627.github.io" # the base hostname & protocol for your site
production_url: "https://samw0627.github.io"
github_username: samw0627
permalink: /blog/:year/:month/:title.html

twitter:
  username: domoritz

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
